import '../province.dart';

Province binhPhuocProvince = Province(
  name: 'Tỉnh Bình Phước',
  districts: [
    District(
      name: 'Huyện Bình Long',
      communes: [
        Commune(name: 'Thị Trấn Bình Long'),
        Commune(name: 'Xã Thanh Lương'),
        Commune(name: 'Xã Thanh Phú'),
        Commune(name: 'Xã Đak Ơ'),
        Commune(name: 'Xã Tân An'),
        Commune(name: 'Xã Tân Bình'),
        Commune(name: 'Xã Hòa Thành'),
        Commune(name: 'Xã An Lộc'),
        Commune(name: 'Xã Phú Riềng'),
        Commune(name: 'Xã Phú Văn'),
        Commune(name: 'Xã Long Hồ'),
        Commune(name: 'Xã Đức Phong'),
        Commune(name: 'Xã Đức Văn'),
        Commune(name: 'Xã Chơn Thành'),
        Commune(name: 'Xã Bình Phú'),
        Commune(name: 'Xã Đồng Nơ'),
        Commune(name: 'Xã Đồng Tiến'),
        Commune(name: 'Xã Đồng Hòa'),
        Commune(name: 'Xã Gia Ray'),
        Commune(name: 'Xã Phước Bình'),
        Commune(name: 'Xã Bù Nho'),
        Commune(name: 'Xã Long Bình'),
        Commune(name: 'Xã Đức Lạc'),
        Commune(name: 'Xã Bình Đức'),
        Commune(name: 'Xã Thanh Bình'),
        Commune(name: 'Xã Thanh Hòa'),
      ],
    ),
    District(
      name: 'Huyện Đồng Phú',
      communes: [
        Commune(name: 'Thị Trấn Đồng Phú'),
        Commune(name: 'Xã Thuận Lợi'),
        Commune(name: 'Xã Tân Phú'),
        Commune(name: 'Xã Phước Thành'),
        Commune(name: 'Xã Tân Tiến'),
        Commune(name: 'Xã Tân Lập'),
        Commune(name: 'Xã Phước Đông'),
        Commune(name: 'Xã Phước Trạch'),
        Commune(name: 'Xã Phước Định'),
        Commune(name: 'Xã Phước Chính'),
        Commune(name: 'Xã Phước Tân'),
        Commune(name: 'Xã Phước Thiện'),
        Commune(name: 'Xã Phước An'),
        Commune(name: 'Xã Phước Hòa'),
        Commune(name: 'Xã Đồng Tâm'),
        Commune(name: 'Xã Đồng Thạnh'),
      ],
    ),
    District(
      name: 'Huyện Bù Đăng',
      communes: [
        Commune(name: 'Thị Trấn Bù Đăng'),
        Commune(name: 'Xã Đak Nhau'),
        Commune(name: 'Xã Phú Sơn'),
        Commune(name: 'Xã Thọ Sơn'),
        Commune(name: 'Xã Đồng Nai'),
        Commune(name: 'Xã Đức Minh'),
        Commune(name: 'Xã Đồng Nà'),
        Commune(name: 'Xã Minh Hưng'),
        Commune(name: 'Xã Đồng Sơn'),
        Commune(name: 'Xã Đức Xuyên'),
        Commune(name: 'Xã Chơn Thành'),
        Commune(name: 'Xã Đồng Kơ'),
        Commune(name: 'Xã Đồng Tâm'),
      ],
    ),
    District(
      name: 'Huyện Bù Đốp',
      communes: [
        Commune(name: 'Thị Trấn Bù Đốp'),
        Commune(name: 'Xã Thuận Lợi'),
        Commune(name: 'Xã Long Bình'),
        Commune(name: 'Xã Thanh Bình'),
        Commune(name: 'Xã Trà Bui'),
        Commune(name: 'Xã Thanh Hoà'),
        Commune(name: 'Xã Hưng Phước'),
        Commune(name: 'Xã Phước Thiện'),
        Commune(name: 'Xã Phước Tín'),
        Commune(name: 'Xã Minh Hưng'),
        Commune(name: 'Xã Phú Vinh'),
        Commune(name: 'Xã Tân Thành'),
        Commune(name: 'Xã Tân Lập'),
        Commune(name: 'Xã Phú Bình'),
        Commune(name: 'Xã Phú Thịnh'),
        Commune(name: 'Xã Thanh An'),
      ],
    ),
    District(
      name: 'Huyện Phú Riềng',
      communes: [
        Commune(name: 'Thị Trấn Phú Riềng'),
        Commune(name: 'Xã Long Phước'),
        Commune(name: 'Xã Bù Nho'),
        Commune(name: 'Xã Long Bình'),
        Commune(name: 'Xã Bình Sơn'),
        Commune(name: 'Xã Long Giang'),
        Commune(name: 'Xã Phước Tân'),
        Commune(name: 'Xã Sơn Giang'),
        Commune(name: 'Xã Bình Giang'),
        Commune(name: 'Xã Bình Phước'),
        Commune(name: 'Xã Long Hưng'),
        Commune(name: 'Xã Long Tân'),
        Commune(name: 'Xã Phước Riềng'),
        Commune(name: 'Xã Bình Hòa'),
        Commune(name: 'Xã An Khương'),
      ],
    ),
    District(
      name: 'Huyện Lộc Ninh',
      communes: [
        Commune(name: 'Thị Trấn Lộc Ninh'),
        Commune(name: 'Xã Lộc Hòa'),
        Commune(name: 'Xã Lộc An'),
        Commune(name: 'Xã Lộc Tấn'),
        Commune(name: 'Xã Lộc Thái'),
        Commune(name: 'Xã Lộc Điền'),
        Commune(name: 'Xã Lộc Thành'),
        Commune(name: 'Xã Lộc Hiệp'),
        Commune(name: 'Xã Lộc Thuận'),
        Commune(name: 'Xã Lộc Quang'),
        Commune(name: 'Xã Lộc Phú'),
        Commune(name: 'Xã Lộc Thịnh'),
        Commune(name: 'Xã Lộc Khánh'),
        Commune(name: 'Xã Lộc Bình'),
        Commune(name: 'Xã Lộc Ninh'),
        Commune(name: 'Xã Lộc Quận'),
        Commune(name: 'Xã Lộc Thủy'),
      ],
    ),
  ],
);
