import '../province.dart';

Province dongThapProvince = Province(
  name: 'Tỉnh Đồng Tháp',
  districts: [
    District(
      name: 'Thành phố Cao Lãnh',
      communes: [
        Commune(name: 'Phường 1'),
        Commune(name: 'Phường 2'),
        Commune(name: 'Phường 3'),
        Commune(name: 'Phường 4'),
        Commune(name: 'Phường 5'),
        Commune(name: 'Phường 6'),
        Commune(name: 'Phường Mỹ Phú'),
        Commune(name: 'Phường Mỹ Long'),
        Commune(name: 'Xã Mỹ Xuyên'),
        Commune(name: 'Xã Mỹ Hòa'),
        Commune(name: 'Xã Mỹ Hội'),
        Commune(name: 'Xã Mỹ Hiệp'),
      ],
    ),
    District(
      name: 'Thành phố Sa Đéc',
      communes: [
        Commune(name: 'Phường 1'),
        Commune(name: 'Phường 2'),
        Commune(name: 'Phường 3'),
        Commune(name: 'Phường 4'),
        Commune(name: 'Phường Tân Khánh Đông'),
        Commune(name: 'Phường Tân Quy Đông'),
        Commune(name: 'Phường An Hoà'),
        Commune(name: 'Phường Tân Quy Tây'),
        Commune(name: 'Phường Tân Phú Đông'),
        Commune(name: 'Xã An Hoà Đông'),
        Commune(name: 'Xã Tân Phú Tây'),
        Commune(name: 'Xã Tân Khánh Tây'),
      ],
    ),
    District(
      name: 'Thị xã Hồng Ngự',
      communes: [
        Commune(name: 'Phường An Lộc'),
        Commune(name: 'Phường An Thạnh'),
        Commune(name: 'Phường An Bình'),
        Commune(name: 'Xã Tân Hội'),
        Commune(name: 'Xã Tân Thành'),
        Commune(name: 'Xã Thường Thới Tiền'),
        Commune(name: 'Xã An Lạc'),
        Commune(name: 'Xã An Hòa'),
        Commune(name: 'Xã Tân Lộc'),
        Commune(name: 'Xã An Phước'),
        Commune(name: 'Xã An Long'),
        Commune(name: 'Xã An Bình B'),
        Commune(name: 'Xã Tân Phú'),
        Commune(name: 'Xã Tân Trung'),
        Commune(name: 'Xã Long Hưng'),
        Commune(name: 'Xã Bình Thạnh Đông'),
        Commune(name: 'Xã Bình Thạnh Tây'),
        Commune(name: 'Xã Long An'),
      ],
    ),
    District(
      name: 'Huyện Lai Vung',
      communes: [
        Commune(name: 'Thị trấn Lai Vung'),
        Commune(name: 'Xã Tân Dương'),
        Commune(name: 'Xã Hòa Thành'),
        Commune(name: 'Xã Long Hậu'),
        Commune(name: 'Xã Long Thắng'),
        Commune(name: 'Xã Vĩnh Thới'),
        Commune(name: 'Xã Tân Phước'),
        Commune(name: 'Xã Hòa Long'),
        Commune(name: 'Xã Tân Thành'),
        Commune(name: 'Xã Long An'),
        Commune(name: 'Xã Long Sơn'),
        Commune(name: 'Xã Phong Hòa'),
        Commune(name: 'Xã Tân Phú'),
        Commune(name: 'Xã Tân Quới'),
      ],
    ),
    District(
      name: 'Huyện Tam Nông',
      communes: [
        Commune(name: 'Thị trấn Tam Nông'),
        Commune(name: 'Xã Phú Thịnh'),
        Commune(name: 'Xã Hậu Lộc'),
        Commune(name: 'Xã Phú Cường'),
        Commune(name: 'Xã Phú Nông'),
        Commune(name: 'Xã Phú Hưng'),
        Commune(name: 'Xã Phú Lộc'),
        Commune(name: 'Xã Phú Quang'),
        Commune(name: 'Xã Phú Vĩnh'),
        Commune(name: 'Xã Phú Thành'),
        Commune(name: 'Xã Phú An'),
        Commune(name: 'Xã Phú Đức'),
        Commune(name: 'Xã Phú Thọ'),
        Commune(name: 'Xã Phú Hồ'),
        Commune(name: 'Xã Phú Hội'),
        Commune(name: 'Xã Phú Lợi'),
        Commune(name: 'Xã Phú Xuân'),
        Commune(name: 'Xã Phú Hiệp'),
        Commune(name: 'Xã Phú Sơn'),
        Commune(name: 'Xã Phú Đông'),
        Commune(name: 'Xã Phú Thịnh'),
      ],
    ),
  ],
);
