
import '../province.dart';

Province haNoiCity = Province(
  name: 'Thành phố Hà Nội',
  districts: [
    District(
      name: 'Quận Ba Đình',
      communes: [
        Commune(name: 'Phường Phúc Xá'),
        Commune(name: 'Phường Trúc Bạch'),
        Commune(name: 'Phường Vĩnh Phúc'),
        Commune(name: 'Phường Cống Vị'),
        Commune(name: 'Phường Liễu Giai'),
        Commune(name: 'Phường Ngọc Hà'),
        Commune(name: 'Phường Điện Biên'),
        Commune(name: 'Phường Đội Cấn'),
        Commune(name: 'Phường Ngọc Khánh'),
        Commune(name: 'Phường Kim Mã'),
        Commune(name: 'Phường Giảng Võ'),
        Commune(name: 'Phường Thành Công'),
      ],
    ),
    District(
      name: 'Quận Hoàn Kiếm',
      communes: [
        Commune(name: 'Phường Phúc Tân'),
        Commune(name: 'Phường Đồng Xuân'),
        Commune(name: 'Phường Hàng Mã'),
        Commune(name: 'Phường Hàng Buồm'),
        Commune(name: 'Phường Hàng Gai'),
        Commune(name: 'Phường Cửa Đông'),
        Commune(name: 'Phường Lý Thái Tổ'),
        Commune(name: 'Phường Hàng Bạc'),
        Commune(name: 'Phường Hàng Đào'),
        Commune(name: 'Phường Hàng Bông'),
        Commune(name: 'Phường Tràng Tiền'),
        Commune(name: 'Phường Trần Hưng Đạo'),
        Commune(name: 'Phường Phan Chu Trinh'),
        Commune(name: 'Phường Hàng Bài'),
      ],
    ),
    District(
      name: 'Quận Hai Bà Trưng',
      communes: [
        Commune(name: 'Phường Thanh Lương'),
        Commune(name: 'Phường Đồng Nhân'),
        Commune(name: 'Phường Phương Mai'),
        Commune(name: 'Phường Quỳnh Lôi'),
        Commune(name: 'Phường Quỳnh Mai'),
        Commune(name: 'Phường Minh Khai'),
        Commune(name: 'Phường Trương Định'),
        Commune(name: 'Phường Thanh Nhàn'),
        Commune(name: 'Phường Cầu Dền'),
        Commune(name: 'Phường Bách Khoa'),
        Commune(name: 'Phường Đồng Tâm'),
        Commune(name: 'Phường Vĩnh Tuy'),
        Commune(name: 'Phường Bạch Mai'),
        Commune(name: 'Phường Quỳnh Xuân'),
        Commune(name: 'Phường Quỳnh Lâm'),
        Commune(name: 'Phường Minh Tân'),
        Commune(name: 'Phường Trung Liệt'),
        Commune(name: 'Phường Quang Trung'),
        Commune(name: 'Phường Trung Tự'),
        Commune(name: 'Phường Kim Liên'),
      ],
    ),
    District(
      name: 'Quận Đống Đa',
      communes: [
        Commune(name: 'Phường Cát Linh'),
        Commune(name: 'Phường Văn Miếu'),
        Commune(name: 'Phường Quốc Tử Giám'),
        Commune(name: 'Phường Láng Thượng'),
        Commune(name: 'Phường Ô Chợ Dừa'),
        Commune(name: 'Phường Văn Chương'),
        Commune(name: 'Phường Hàng Bột'),
        Commune(name: 'Phường Láng Hạ'),
        Commune(name: 'Phường Khâm Thiên'),
        Commune(name: 'Phường Thổ Quan'),
        Commune(name: 'Phường Nam Đồng'),
        Commune(name: 'Phường Trung Phụng'),
        Commune(name: 'Phường Quang Trung'),
        Commune(name: 'Phường Trung Liệt'),
        Commune(name: 'Phường Phương Liên'),
        Commune(name: 'Phường Thịnh Quang'),
        Commune(name: 'Phường Trung Tự'),
        Commune(name: 'Phường Kim Liên'),
        Commune(name: 'Phường Phương Mai'),
        Commune(name: 'Phường Ngã Tư Sở'),
        Commune(name: 'Phường Khương Thượng'),
        Commune(name: 'Phường Nhân Chính'),
        Commune(name: 'Phường Thượng Đình'),
        Commune(name: 'Phường Khương Trung'),
        Commune(name: 'Phường Kim Mã'),
        Commune(name: 'Phường Quốc Tử Giám'),
      ],
    ),
  ],
);
