import '../province.dart';

Province hoChiMinhCity = Province(
  name: 'Thành phố Hồ Chí Minh',
  districts: [
    District(
      name: 'Quận 1',
      communes: [
        Commune(name: 'Phường Nguyễn Thái Bình'),
        Commune(name: 'Phường Bến Thành'),
        Commune(name: 'Phường Cầu Kho'),
        Commune(name: 'Phường Cầu Ông Lãnh'),
        Commune(name: 'Phường Cô Giang'),
        Commune(name: 'Phường Đa Kao'),
        Commune(name: 'Phường Nguyễn Cư Trinh'),
        Commune(name: 'Phường Nguyễn Thái Bình'),
        Commune(name: 'Phường Phạm Ngũ Lão'),
        Commune(name: 'Phường Tân Định'),
      ],
    ),
    District(
      name: 'Quận 2',
      communes: [
        Commune(name: 'Phường An Phú'),
        Commune(name: 'Phường Thảo Điền'),
        Commune(name: 'Phường Bình An'),
        Commune(name: 'Phường Bình Khánh'),
        Commune(name: 'Phường An Khánh'),
        Commune(name: 'Phường Thủ Thiêm'),
        Commune(name: 'Phường Bình Trưng Đông'),
        Commune(name: 'Phường Bình Trưng Tây'),
      ],
    ),
    District(
      name: 'Quận 3',
      communes: [
        Commune(name: 'Phường 1'),
        Commune(name: 'Phường 2'),
        Commune(name: 'Phường 3'),
        Commune(name: 'Phường 4'),
        Commune(name: 'Phường 5'),
        Commune(name: 'Phường 6'),
        Commune(name: 'Phường 7'),
        Commune(name: 'Phường 8'),
        Commune(name: 'Phường 9'),
        Commune(name: 'Phường 10'),
        Commune(name: 'Phường 11'),
        Commune(name: 'Phường 12'),
        Commune(name: 'Phường 13'),
        Commune(name: 'Phường 14'),
        Commune(name: 'Phường 15'),
        Commune(name: 'Phường 16'),
      ],
    ),
    District(
      name: 'Quận 4',
      communes: [
        Commune(name: 'Phường 1'),
        Commune(name: 'Phường 2'),
        Commune(name: 'Phường 3'),
        Commune(name: 'Phường 4'),
        Commune(name: 'Phường 5'),
        Commune(name: 'Phường 6'),
        Commune(name: 'Phường 7'),
        Commune(name: 'Phường 8'),
        Commune(name: 'Phường 9'),
        Commune(name: 'Phường 10'),
        Commune(name: 'Phường 11'),
        Commune(name: 'Phường 12'),
        Commune(name: 'Phường 13'),
        Commune(name: 'Phường 14'),
        Commune(name: 'Phường 15'),
        Commune(name: 'Phường 16'),
      ],
    ),
    District(
      name: 'Quận 5',
      communes: [
        Commune(name: 'Phường 1'),
        Commune(name: 'Phường 2'),
        Commune(name: 'Phường 3'),
        Commune(name: 'Phường 4'),
        Commune(name: 'Phường 5'),
        Commune(name: 'Phường 6'),
        Commune(name: 'Phường 7'),
        Commune(name: 'Phường 8'),
        Commune(name: 'Phường 9'),
        Commune(name: 'Phường 10'),
        Commune(name: 'Phường 11'),
        Commune(name: 'Phường 12'),
        Commune(name: 'Phường 13'),
        Commune(name: 'Phường 14'),
        Commune(name: 'Phường 15'),
        Commune(name: 'Phường 16'),
      ],
    ),
    District(
      name: 'Quận 6',
      communes: [
        Commune(name: 'Phường 1'),
        Commune(name: 'Phường 2'),
        Commune(name: 'Phường 3'),
        Commune(name: 'Phường 4'),
        Commune(name: 'Phường 5'),
        Commune(name: 'Phường 6'),
        Commune(name: 'Phường 7'),
        Commune(name: 'Phường 8'),
        Commune(name: 'Phường 9'),
        Commune(name: 'Phường 10'),
        Commune(name: 'Phường 11'),
        Commune(name: 'Phường 12'),
        Commune(name: 'Phường 13'),
        Commune(name: 'Phường 14'),
        Commune(name: 'Phường 15'),
        Commune(name: 'Phường 16'),
      ],
    ),
    District(
      name: 'Quận 7',
      communes: [
        Commune(name: 'Phường Phú Mỹ'),
        Commune(name: 'Phường Tân Phú'),
        Commune(name: 'Phường Tân Thuận Đông'),
        Commune(name: 'Phường Tân Thuận Tây'),
        Commune(name: 'Phường Tân Kiểng'),
        Commune(name: 'Phường Tân Hưng'),
        Commune(name: 'Phường Bình Thuận'),
        Commune(name: 'Phường Phú Thuận'),
        Commune(name: 'Phường Tân Quy'),
        Commune(name: 'Phường Tân Phong'),
        Commune(name: 'Phường Phú Mỹ Hưng'),
        Commune(name: 'Phường Tân Hưng Thuận'),
        Commune(name: 'Phường Tân Quy Đông'),
        Commune(name: 'Phường Tân Quy Tây'),
      ],
    ),
    District(
      name: 'Quận 8',
      communes: [
        Commune(name: 'Phường 1'),
        Commune(name: 'Phường 2'),
        Commune(name: 'Phường 3'),
        Commune(name: 'Phường 4'),
        Commune(name: 'Phường 5'),
        Commune(name: 'Phường 6'),
        Commune(name: 'Phường 7'),
        Commune(name: 'Phường 8'),
        Commune(name: 'Phường 9'),
        Commune(name: 'Phường 10'),
        Commune(name: 'Phường 11'),
        Commune(name: 'Phường 12'),
        Commune(name: 'Phường 13'),
        Commune(name: 'Phường 14'),
        Commune(name: 'Phường 15'),
        Commune(name: 'Phường 16'),
        Commune(name: 'Phường Bình Hưng Hòa'),
        Commune(name: 'Phường Bình Hưng Hoà A'),
        Commune(name: 'Phường Bình Hưng Hoà B'),
        Commune(name: 'Phường Bình Trị Đông'),
        Commune(name: 'Phường Bình Trị Đông A'),
        Commune(name: 'Phường Bình Trị Đông B'),
      ],
    ),
    District(
      name: 'Quận 9',
      communes: [
        Commune(name: 'Phường Long Bình'),
        Commune(name: 'Phường Long Thạnh Mỹ'),
        Commune(name: 'Phường Tân Phú'),
        Commune(name: 'Phường Hiệp Phú'),
        Commune(name: 'Phường Tăng Nhơn Phú A'),
        Commune(name: 'Phường Tăng Nhơn Phú B'),
        Commune(name: 'Phường Phước Long B'),
        Commune(name: 'Phường Phước Long A'),
        Commune(name: 'Phường Trường Thạnh'),
        Commune(name: 'Phường Long Phước'),
        Commune(name: 'Phường Long Trường'),
        Commune(name: 'Phường Phước Bình'),
        Commune(name: 'Phường Phú Hữu'),
      ],
    ),
    District(
      name: 'Quận 10',
      communes: [
        Commune(name: 'Phường 1'),
        Commune(name: 'Phường 2'),
        Commune(name: 'Phường 3'),
        Commune(name: 'Phường 4'),
        Commune(name: 'Phường 5'),
        Commune(name: 'Phường 6'),
        Commune(name: 'Phường 7'),
        Commune(name: 'Phường 8'),
        Commune(name: 'Phường 9'),
        Commune(name: 'Phường 10'),
        Commune(name: 'Phường 11'),
        Commune(name: 'Phường 12'),
        Commune(name: 'Phường 13'),
        Commune(name: 'Phường 14'),
        Commune(name: 'Phường 15'),
      ],
    ),
    District(
      name: 'Quận 11',
      communes: [
        Commune(name: 'Phường 1'),
        Commune(name: 'Phường 2'),
        Commune(name: 'Phường 3'),
        Commune(name: 'Phường 4'),
        Commune(name: 'Phường 5'),
        Commune(name: 'Phường 6'),
        Commune(name: 'Phường 7'),
        Commune(name: 'Phường 8'),
        Commune(name: 'Phường 9'),
        Commune(name: 'Phường 10'),
        Commune(name: 'Phường 11'),
        Commune(name: 'Phường 12'),
        Commune(name: 'Phường 13'),
        Commune(name: 'Phường 14'),
        Commune(name: 'Phường 15'),
        Commune(name: 'Phường 16'),
      ],
    ),
    District(
      name: 'Quận 12',
      communes: [
        Commune(name: 'Phường Thạnh Lộc'),
        Commune(name: 'Phường Thạnh Xuân'),
        Commune(name: 'Phường Thới An'),
        Commune(name: 'Phường Tân Chánh Hiệp'),
        Commune(name: 'Phường An Phú Đông'),
        Commune(name: 'Phường Tân Thới Hiệp'),
        Commune(name: 'Phường Trung Mỹ Tây'),
        Commune(name: 'Phường Tân Hưng Thuận'),
        Commune(name: 'Phường Đông Hưng Thuận'),
        Commune(name: 'Phường Tân Thới Nhất'),
        Commune(name: 'Phường Linh Xuân'),
        Commune(name: 'Phường Bình Chiểu'),
        Commune(name: 'Phường An Phú Đông'),
        Commune(name: 'Phường Tân Thới Hiệp'),
        Commune(name: 'Phường Trung Mỹ Tây'),
        Commune(name: 'Phường Tân Hưng Thuận'),
        Commune(name: 'Phường Đông Hưng Thuận'),
        Commune(name: 'Phường Tân Thới Nhất'),
        Commune(name: 'Phường Linh Xuân'),
        Commune(name: 'Phường Bình Chiểu'),
      ],
    ),
    District(
      name: 'Quận Bình Tân',
      communes: [
        Commune(name: 'Phường Bình Hưng Hòa'),
        Commune(name: 'Phường Bình Hưng Hoà A'),
        Commune(name: 'Phường Bình Hưng Hoà B'),
        Commune(name: 'Phường Bình Trị Đông'),
        Commune(name: 'Phường Bình Trị Đông A'),
        Commune(name: 'Phường Bình Trị Đông B'),
        Commune(name: 'Phường Tân Tạo'),
        Commune(name: 'Phường Tân Tạo A'),
        Commune(name: 'Phường An Lạc'),
        Commune(name: 'Phường An Lạc A'),
        Commune(name: 'Phường An Lạc B'),
        Commune(name: 'Phường Tân Thới Hiệp'),
        Commune(name: 'Phường Tân Thới Nhất'),
        Commune(name: 'Phường Tân Chánh Hiệp'),
        Commune(name: 'Phường Tân Hòa Đông'),
        Commune(name: 'Phường Tân Hòa Đông A'),
        Commune(name: 'Phường Tân Hòa Đông B'),
        Commune(name: 'Phường Bình Hưng Hoà'),
        Commune(name: 'Phường Bình Hưng Hoà A'),
        Commune(name: 'Phường Bình Hưng Hoà B'),
        Commune(name: 'Phường Bình Trị Đông'),
        Commune(name: 'Phường Bình Trị Đông A'),
        Commune(name: 'Phường Bình Trị Đông B'),
        Commune(name: 'Phường Tân Tạo'),
        Commune(name: 'Phường Tân Tạo A'),
        Commune(name: 'Phường An Lạc'),
        Commune(name: 'Phường An Lạc A'),
        Commune(name: 'Phường An Lạc B'),
        Commune(name: 'Phường Tân Thới Hiệp'),
        Commune(name: 'Phường Tân Thới Nhất'),
        Commune(name: 'Phường Tân Chánh Hiệp'),
        Commune(name: 'Phường Tân Hòa Đông'),
        Commune(name: 'Phường Tân Hòa Đông A'),
        Commune(name: 'Phường Tân Hòa Đông B'),
      ],
    ),
    District(
      name: 'Quận Bình Thạnh',
      communes: [
        Commune(name: 'Phường 1'),
        Commune(name: 'Phường 2'),
        Commune(name: 'Phường 3'),
        Commune(name: 'Phường 4'),
        Commune(name: 'Phường 5'),
        Commune(name: 'Phường 6'),
        Commune(name: 'Phường 7'),
        Commune(name: 'Phường 8'),
        Commune(name: 'Phường 9'),
        Commune(name: 'Phường 10'),
        Commune(name: 'Phường 11'),
        Commune(name: 'Phường 12'),
        Commune(name: 'Phường 13'),
        Commune(name: 'Phường 14'),
        Commune(name: 'Phường 15'),
        Commune(name: 'Phường 16'),
        Commune(name: 'Phường 17'),
        Commune(name: 'Phường 18'),
        Commune(name: 'Phường 19'),
        Commune(name: 'Phường 20'),
        Commune(name: 'Phường 21'),
        Commune(name: 'Phường 22'),
        Commune(name: 'Phường 23'),
        Commune(name: 'Phường 24'),
        Commune(name: 'Phường 25'),
        Commune(name: 'Phường 26'),
        Commune(name: 'Phường 27'),
        Commune(name: 'Phường 28'),
        Commune(name: 'Phường 29'),
        Commune(name: 'Phường 30'),
        Commune(name: 'Phường 31'),
        Commune(name: 'Phường 32'),
        Commune(name: 'Phường 33'),
        Commune(name: 'Phường 34'),
        Commune(name: 'Phường 35'),
        Commune(name: 'Phường 36'),
        Commune(name: 'Phường 37'),
        Commune(name: 'Phường 38'),
        Commune(name: 'Phường 39'),
        Commune(name: 'Phường 40'),
        Commune(name: 'Phường 41'),
      ],
    ),
    District(
      name: 'Quận Gò Vấp',
      communes: [
        Commune(name: 'Phường 1'),
        Commune(name: 'Phường 2'),
        Commune(name: 'Phường 3'),
        Commune(name: 'Phường 4'),
        Commune(name: 'Phường 5'),
        Commune(name: 'Phường 6'),
        Commune(name: 'Phường 7'),
        Commune(name: 'Phường 8'),
        Commune(name: 'Phường 9'),
        Commune(name: 'Phường 10'),
        Commune(name: 'Phường 11'),
        Commune(name: 'Phường 12'),
        Commune(name: 'Phường 13'),
        Commune(name: 'Phường 14'),
        Commune(name: 'Phường 15'),
        Commune(name: 'Phường 16'),
      ],
    ),
    District(
      name: 'Quận Phú Nhuận',
      communes: [
        Commune(name: 'Phường 1'),
        Commune(name: 'Phường 2'),
        Commune(name: 'Phường 3'),
        Commune(name: 'Phường 4'),
        Commune(name: 'Phường 5'),
        Commune(name: 'Phường 6'),
        Commune(name: 'Phường 7'),
        Commune(name: 'Phường 8'),
        Commune(name: 'Phường 9'),
        Commune(name: 'Phường 10'),
        Commune(name: 'Phường 11'),
        Commune(name: 'Phường 12'),
        Commune(name: 'Phường 13'),
        Commune(name: 'Phường 14'),
        Commune(name: 'Phường 15'),
        Commune(name: 'Phường 16'),
        Commune(name: 'Phường 17'),
      ],
    ),
    District(
      name: 'Quận Tân Bình',
      communes: [
        Commune(name: 'Phường 1'),
        Commune(name: 'Phường 2'),
        Commune(name: 'Phường 3'),
        Commune(name: 'Phường 4'),
        Commune(name: 'Phường 5'),
        Commune(name: 'Phường 6'),
        Commune(name: 'Phường 7'),
        Commune(name: 'Phường 8'),
        Commune(name: 'Phường 9'),
        Commune(name: 'Phường 10'),
        Commune(name: 'Phường 11'),
        Commune(name: 'Phường 12'),
        Commune(name: 'Phường 13'),
        Commune(name: 'Phường 14'),
        Commune(name: 'Phường 15'),
        Commune(name: 'Phường 16'),
      ],
    ),
    District(
      name: 'Quận Tân Phú',
      communes: [
        Commune(name: 'Phường Tân Sơn Nhì'),
        Commune(name: 'Phường Tây Thạnh'),
        Commune(name: 'Phường Sơn Kỳ'),
        Commune(name: 'Phường Tân Quý'),
        Commune(name: 'Phường Tân Thành'),
        Commune(name: 'Phường Phú Thọ Hoà'),
        Commune(name: 'Phường Phú Thạnh'),
        Commune(name: 'Phường Phú Trung'),
        Commune(name: 'Phường Hòa Thạnh'),
        Commune(name: 'Phường Hiệp Tân'),
        Commune(name: 'Phường Tân Thới Hoà'),
        Commune(name: 'Phường Bình Hưng Hoà'),
        Commune(name: 'Phường Bình Hưng Hoà A'),
        Commune(name: 'Phường Bình Hưng Hoà B'),
        Commune(name: 'Phường Tân Hưng Thuận'),
        Commune(name: 'Phường Tân Hưng Thuận A'),
        Commune(name: 'Phường Tân Hưng Thuận B'),
      ],
    ),
    District(
      name: 'Quận Thủ Đức',
      communes: [
        Commune(name: 'Phường Linh Xuân'),
        Commune(name: 'Phường Bình Chiểu'),
        Commune(name: 'Phường Linh Trung'),
        Commune(name: 'Phường Tam Bình'),
        Commune(name: 'Phường Tam Phú'),
        Commune(name: 'Phường Hiệp Bình Phước'),
        Commune(name: 'Phường Hiệp Bình Chánh'),
        Commune(name: 'Phường Linh Chiểu'),
        Commune(name: 'Phường Linh Tây'),
        Commune(name: 'Phường Linh Đông'),
        Commune(name: 'Phường Bình Thọ'),
        Commune(name: 'Phường Trường Thọ'),
        Commune(name: 'Phường Long Bình'),
        Commune(name: 'Phường Long Thạnh Mỹ'),
        Commune(name: 'Phường Tân Phú'),
        Commune(name: 'Phường Hiệp Phú'),
        Commune(name: 'Phường Tăng Nhơn Phú A'),
        Commune(name: 'Phường Tăng Nhơn Phú B'),
        Commune(name: 'Phường Phước Long B'),
        Commune(name: 'Phường Phước Long A'),
      ],
    ),
    District(
      name: 'Huyện Bình Chánh',
      communes: [
        Commune(name: 'Xã An Phú Tây'),
        Commune(name: 'Xã Bình Chánh'),
        Commune(name: 'Xã Bình Hưng'),
        Commune(name: 'Xã Bình Lợi'),
        Commune(name: 'Xã Đa Phước'),
        Commune(name: 'Xã Hưng Long'),
        Commune(name: 'Xã Lê Minh Xuân'),
        Commune(name: 'Xã Phạm Văn Hai'),
        Commune(name: 'Xã Phong Phú'),
        Commune(name: 'Xã Quy Đức'),
        Commune(name: 'Xã Quy Đức'),
        Commune(name: 'Xã Tân Kiên'),
        Commune(name: 'Xã Tân Nhựt'),
        Commune(name: 'Xã Tân Quý Tây'),
        Commune(name: 'Xã Vĩnh Lộc A'),
        Commune(name: 'Xã Vĩnh Lộc B'),
        Commune(name: 'Xã Xuân Thới Đông'),
        Commune(name: 'Xã Xuân Thới Sơn'),
      ],
    ),
    District(
      name: 'Huyện Cần Giờ',
      communes: [
        Commune(name: 'Xã An Thới Đông'),
        Commune(name: 'Xã Bình Khánh'),
        Commune(name: 'Xã Cần Thạnh'),
        Commune(name: 'Xã Long Hòa'),
        Commune(name: 'Xã Lý Nhơn'),
        Commune(name: 'Xã Tam Thôn Hiệp'),
        Commune(name: 'Xã Thạnh An'),
        Commune(name: 'Xã Thạnh Lộc'),
        Commune(name: 'Xã Thạnh Mỹ'),
        Commune(name: 'Xã Vườn Điều'),
      ],
    ),
    District(
      name: 'Huyện Củ Chi',
      communes: [
        Commune(name: 'Xã An Nhơn Tây'),
        Commune(name: 'Xã An Phú'),
        Commune(name: 'Xã Bình Mỹ'),
        Commune(name: 'Xã Hòa Phú'),
        Commune(name: 'Xã Nhuận Đức'),
        Commune(name: 'Xã Phạm Văn Cội'),
        Commune(name: 'Xã Phú Hòa Đông'),
        Commune(name: 'Xã Phú Mỹ Hưng'),
        Commune(name: 'Xã Phước Hiệp'),
        Commune(name: 'Xã Phước Thạnh'),
        Commune(name: 'Xã Phước Vĩnh An'),
        Commune(name: 'Xã Tân An Hội'),
        Commune(name: 'Xã Tân Phú Trung'),
        Commune(name: 'Xã Tân Thạnh Đông'),
        Commune(name: 'Xã Tân Thạnh Tây'),
        Commune(name: 'Xã Tân Thông Hội'),
        Commune(name: 'Xã Trung An'),
        Commune(name: 'Xã Trung Lập Hạ'),
        Commune(name: 'Xã Trung Lập Thượng'),
      ],
    ),
    District(
      name: 'Huyện Hóc Môn',
      communes: [
        Commune(name: 'Xã Bà Điểm'),
        Commune(name: 'Xã Đông Thạnh'),
        Commune(name: 'Xã Hóc Môn'),
        Commune(name: 'Xã Nhị Bình'),
        Commune(name: 'Xã Tân Hiệp'),
        Commune(name: 'Xã Tân Thới Nhì'),
        Commune(name: 'Xã Tân Xuân'),
        Commune(name: 'Xã Thới Tam Thôn'),
        Commune(name: 'Xã Trung Chánh'),
        Commune(name: 'Xã Xuân Thới Đông'),
        Commune(name: 'Xã Xuân Thới Sơn'),
        Commune(name: 'Xã Xuân Thới Thượng'),
      ],
    ),
    District(
      name: 'Huyện Nhà Bè',
      communes: [
        Commune(name: 'Phường Nhà Bè'),
        Commune(name: 'Phường Phước Kiển'),
        Commune(name: 'Phường Phước Lộc'),
        Commune(name: 'Phường Phước Long A'),
        Commune(name: 'Phường Phước Long B'),
        Commune(name: 'Phường Phước Thạnh'),
        Commune(name: 'Phường Phú Xuân'),
        Commune(name: 'Phường Rạch Đĩa'),
        Commune(name: 'Phường Tam Đông'),
        Commune(name: 'Phường Tam Phú'),
      ],
    ),
  ],
);
