import '../province.dart';

Province longAnProvince = Province(
  name: 'Tỉnh Long An',
  districts: [
    District(
      name: 'Thành phố Tân An',
      communes: [
        Commune(name: 'Phường 1'),
        Commune(name: 'Phường 2'),
        Commune(name: 'Phường 3'),
        Commune(name: 'Phường 4'),
        Commune(name: 'Phường 5'),
        Commune(name: 'Phường 6'),
        Commune(name: 'Phường 7'),
        Commune(name: 'Phường 8'),
        Commune(name: 'Phường 9'),
        Commune(name: 'Xã Tân Khánh'),
        Commune(name: 'Xã An Vĩnh Ngãi'),
        Commune(name: 'Xã Tân Quý Đông'),
        Commune(name: 'Xã Bình Tâm'),
        Commune(name: 'Xã Tân Hiệp'),
        Commune(name: 'Xã Tân Hội'),
        Commune(name: 'Xã Tân Thành'),
        Commune(name: 'Xã Tân Đông'),
        Commune(name: 'Xã Khánh Hậu'),
      ],
    ),
    District(
      name: 'Huyện Bến Lức',
      communes: [
        Commune(name: 'Thị trấn Bến Lức'),
        Commune(name: 'Xã Thạnh Lợi'),
        Commune(name: 'Xã Lương Bình'),
        Commune(name: 'Xã Lương Hòa'),
        Commune(name: 'Xã Tân Hòa'),
        Commune(name: 'Xã Tân Bửu'),
        Commune(name: 'Xã An Thạnh'),
        Commune(name: 'Xã Bình Đức'),
        Commune(name: 'Xã Mỹ Yên'),
        Commune(name: 'Xã Thanh Phú'),
        Commune(name: 'Xã Long Hiệp'),
        Commune(name: 'Xã Thạnh Đức'),
        Commune(name: 'Xã Phước Lợi'),
        Commune(name: 'Xã Nhựt Chánh'),
        Commune(name: 'Xã Phước Hậu'),
        Commune(name: 'Xã Mỹ Phước'),
        Commune(name: 'Xã Thanh Vĩnh Đông'),
        Commune(name: 'Xã Tân Thanh'),
        Commune(name: 'Xã Long Định'),
        Commune(name: 'Xã Thạnh Hòa'),
        Commune(name: 'Xã Đức Hòa'),
        Commune(name: 'Xã An Lục Long'),
      ],
    ),
    District(
      name: 'Huyện Cần Đước',
      communes: [
        Commune(name: 'Thị trấn Cần Đước'),
        Commune(name: 'Xã Long Trạch'),
        Commune(name: 'Xã Long Khê'),
        Commune(name: 'Xã Long Định'),
        Commune(name: 'Xã Phước Vân'),
        Commune(name: 'Xã Long Hòa'),
        Commune(name: 'Xã Long Cang'),
        Commune(name: 'Xã Long Sơn'),
        Commune(name: 'Xã Long Hiệp'),
        Commune(name: 'Xã Phước Đông'),
        Commune(name: 'Xã Long An'),
        Commune(name: 'Xã Tân Chánh'),
        Commune(name: 'Xã Phước Tuy'),
        Commune(name: 'Xã Long Phụng'),
        Commune(name: 'Xã Đông Thạnh'),
        Commune(name: 'Xã Tân Lân'),
        Commune(name: 'Xã Đông Thành'),
        Commune(name: 'Xã Phước Vĩnh Tây'),
        Commune(name: 'Xã Long Hựu Tây'),
        Commune(name: 'Xã Tân Ân'),
      ],
    ),
    District(
      name: 'Huyện Cần Giuộc',
      communes: [
        Commune(name: 'Thị trấn Cần Giuộc'),
        Commune(name: 'Xã Phước Lý'),
        Commune(name: 'Xã Long Thượng'),
        Commune(name: 'Xã Long Hậu'),
        Commune(name: 'Xã Tân Kim'),
        Commune(name: 'Xã Phước Hậu'),
        Commune(name: 'Xã Mỹ Lộc'),
        Commune(name: 'Xã Phước Lại'),
        Commune(name: 'Xã Phước Lâm'),
        Commune(name: 'Xã Trường Bình'),
        Commune(name: 'Xã Long An'),
        Commune(name: 'Xã Long Phụng'),
        Commune(name: 'Xã Phước Vân'),
        Commune(name: 'Xã Long Định'),
        Commune(name: 'Xã Tân Tập'),
        Commune(name: 'Xã Tân Điền'),
        Commune(name: 'Xã Phước Tân Hưng'),
        Commune(name: 'Xã Long Thanh'),
        Commune(name: 'Xã Đông Thạnh'),
        Commune(name: 'Xã Tân Hựu'),
        Commune(name: 'Xã Mỹ Phước'),
        Commune(name: 'Xã Phước Lưu'),
        Commune(name: 'Xã Phước Hòa'),
      ],
    ),
    District(
      name: 'Huyện Châu Thành',
      communes: [
        Commune(name: 'Thị trấn Tầm Vu'),
        Commune(name: 'Xã Bình Quới'),
        Commune(name: 'Xã Hòa Phú'),
        Commune(name: 'Xã Phú Ngãi Trị'),
        Commune(name: 'Xã Vĩnh Công'),
        Commune(name: 'Xã Thuận Mỹ'),
        Commune(name: 'Xã Hiệp Thạnh'),
        Commune(name: 'Xã Thanh Phú Long'),
        Commune(name: 'Xã Dương Xuân Hội'),
        Commune(name: 'Xã An Lục Đồng'),
        Commune(name: 'Xã An Thạnh'),
        Commune(name: 'Xã Long Trì'),
        Commune(name: 'Xã Thanh Vĩnh Đông'),
        Commune(name: 'Xã Tân Lân'),
        Commune(name: 'Xã Bình Lãng'),
        Commune(name: 'Xã Tam Phước'),
        Commune(name: 'Xã Phước Tân Hưng'),
        Commune(name: 'Xã Phước Vinh Tây'),
        Commune(name: 'Xã Long Phước'),
      ],
    ),
    District(
      name: 'Huyện Đức Hòa',
      communes: [
        Commune(name: 'Thị trấn Đức Hòa'),
        Commune(name: 'Xã Hòa Khánh Đông'),
        Commune(name: 'Xã Mỹ Hạnh Bắc'),
        Commune(name: 'Xã Hòa Khánh Nam'),
        Commune(name: 'Xã Hòa Long'),
        Commune(name: 'Xã Hòa Xuân Đông'),
        Commune(name: 'Xã Hòa Hiệp'),
        Commune(name: 'Xã Hòa Quang Bắc'),
        Commune(name: 'Xã Hòa Xuyên'),
        Commune(name: 'Xã Hòa Sơn'),
        Commune(name: 'Xã Hòa Phú'),
        Commune(name: 'Xã Hòa Bình'),
        Commune(name: 'Xã Hòa Phước'),
        Commune(name: 'Xã Hòa Khánh Tây'),
        Commune(name: 'Xã Hòa Xuân Tây'),
        Commune(name: 'Xã Hòa Long'),
        Commune(name: 'Xã Hòa Thạnh'),
        Commune(name: 'Xã Hòa An'),
        Commune(name: 'Xã Hòa Đông'),
        Commune(name: 'Xã Hòa Tân'),
        Commune(name: 'Xã Hòa Thành'),
      ],
    ),
    District(
      name: 'Huyện Đức Huệ',
      communes: [
        Commune(name: 'Thị trấn Đức Huệ'),
        Commune(name: 'Xã Lộc Giang'),
        Commune(name: 'Xã Mỹ Thành Bắc'),
        Commune(name: 'Xã Mỹ Thạnh Bắc'),
        Commune(name: 'Xã Hậu Nghĩa'),
        Commune(name: 'Xã Hiệp Hòa'),
        Commune(name: 'Xã Đức Hòa Thượng'),
        Commune(name: 'Xã Mỹ Thạnh Tây'),
        Commune(name: 'Xã Mỹ Thành Nam'),
        Commune(name: 'Xã Đức Hòa Đông'),
        Commune(name: 'Xã Đức Lập Hạ'),
        Commune(name: 'Xã Đức Hòa Hạ'),
        Commune(name: 'Xã Tân Mỹ'),
        Commune(name: 'Xã Hòa Khánh Đông'),
        Commune(name: 'Xã Hòa Khánh Nam'),
        Commune(name: 'Xã Đức Lập Thượng'),
        Commune(name: 'Xã Hòa Khánh Tây'),
      ],
    ),
    District(
      name: 'Huyện Mộc Hóa',
      communes: [
        Commune(name: 'Thị trấn Mộc Hóa'),
        Commune(name: 'Xã Bình Hiệp'),
        Commune(name: 'Xã Bình Hòa Nam'),
        Commune(name: 'Xã Bình Thạnh'),
        Commune(name: 'Xã Bình Hòa Bắc'),
        Commune(name: 'Xã Thạnh Hưng'),
        Commune(name: 'Xã Tân Lập'),
        Commune(name: 'Xã Tân Thành'),
        Commune(name: 'Xã Phước Tuy'),
        Commune(name: 'Xã Tân Thạnh'),
        Commune(name: 'Xã Tân Hiệp'),
        Commune(name: 'Xã Tân Hòa'),
        Commune(name: 'Xã Thuận Bình'),
        Commune(name: 'Xã Thành Thạnh'),
        Commune(name: 'Xã Hậu Thạnh Đông'),
        Commune(name: 'Xã Hậu Thạnh Tây'),
        Commune(name: 'Xã Tân Định'),
        Commune(name: 'Xã Định Thành'),
        Commune(name: 'Xã Tân Thới'),
        Commune(name: 'Xã Phước Hiệp'),
        Commune(name: 'Xã Tân Hưng'),
        Commune(name: 'Xã Tân Thạnh Đông'),
        Commune(name: 'Xã Tân Hiệp A'),
      ],
    ),
    District(
      name: 'Huyện Tân Hưng',
      communes: [
        Commune(name: 'Thị trấn Tân Hưng'),
        Commune(name: 'Xã Hưng Hà'),
        Commune(name: 'Xã Hưng Điền A'),
        Commune(name: 'Xã Hưng Điền B'),
        Commune(name: 'Xã Tân Lễ'),
        Commune(name: 'Xã Định Cư'),
        Commune(name: 'Xã Thạnh Hưng'),
        Commune(name: 'Xã An Vĩnh Ngãi'),
        Commune(name: 'Xã Vĩnh Châu Bắc'),
        Commune(name: 'Xã Vĩnh Châu Nam'),
        Commune(name: 'Xã Thạnh Phú'),
        Commune(name: 'Xã Thạnh Phong'),
        Commune(name: 'Xã Thạnh Lộc'),
        Commune(name: 'Xã Thạnh Hưng'),
        Commune(name: 'Xã Tân Hưng Đông'),
        Commune(name: 'Xã Tân Hưng Thuận'),
        Commune(name: 'Xã Tân Thành'),
        Commune(name: 'Xã Tân Hưng A'),
      ],
    ),
    District(
      name: 'Huyện Tân Thạnh',
      communes: [
        Commune(name: 'Thị trấn Tân Thạnh'),
        Commune(name: 'Xã Bắc Hòa'),
        Commune(name: 'Xã Hậu Thạnh Tây'),
        Commune(name: 'Xã Hậu Thạnh Đông'),
        Commune(name: 'Xã Kiến Bình'),
        Commune(name: 'Xã Đông Hòa'),
        Commune(name: 'Xã Thành Trung'),
        Commune(name: 'Xã Tân Lập'),
        Commune(name: 'Xã Tân Thành'),
        Commune(name: 'Xã Tân Phước'),
        Commune(name: 'Xã Thuận Bình'),
        Commune(name: 'Xã Điền Hòa'),
        Commune(name: 'Xã Điền Lộc'),
        Commune(name: 'Xã Đông Thành'),
        Commune(name: 'Xã Đông Hòa Hưng'),
        Commune(name: 'Xã Tân Hòa'),
        Commune(name: 'Xã Điền Hòa Đông'),
        Commune(name: 'Xã Tân Đông'),
        Commune(name: 'Xã Tân Hiệp'),
        Commune(name: 'Xã Đông Hòa Đông'),
        Commune(name: 'Xã Tân Thành'),
      ],
    ),
    District(
      name: 'Huyện Tân Trụ',
      communes: [
        Commune(name: 'Th       '),
        Commune(name: 'Xã Bình Lãng'),
        Commune(name: 'Xã Lạc Tấn'),
        Commune(name: 'Xã Long Hòa'),
        Commune(name: 'Xã Long Thượng'),
        Commune(name: 'Xã Long Thuận'),
        Commune(name: 'Xã Long Thuỷ'),
        Commune(name: 'Xã Nhị Bình'),
        Commune(name: 'Xã Hòa Bình'),
        Commune(name: 'Xã Thạnh Hòa'),
        Commune(name: 'Xã Thạnh Trị'),
        Commune(name: 'Xã Thạnh Phước'),
        Commune(name: 'Xã Tân Phú'),
        Commune(name: 'Xã Hòa Khánh Tây'),
        Commune(name: 'Xã Bình Tịnh'),
        Commune(name: 'Xã Hậu Lộc'),
        Commune(name: 'Xã Tân Bình'),
        Commune(name: 'Xã Bình Phú'),
        Commune(name: 'Xã Tân Lập'),
        Commune(name: 'Xã Tân Hòa'),
        Commune(name: 'Xã Bình Nghị'),
        Commune(name: 'Xã Tân Thành'),
      ],
    ),
    District(
      name: 'Huyện Thạnh Hóa',
      communes: [
        Commune(name: 'Thị trấn Thạnh Hóa'),
        Commune(name: 'Xã Tân Hòa'),
        Commune(name: 'Xã Xuân Đông'),
        Commune(name: 'Xã Xuân Tây'),
        Commune(name: 'Xã Thạnh Phước'),
        Commune(name: 'Xã Tân Đông'),
        Commune(name: 'Xã Xuân Đông'),
        Commune(name: 'Xã Xuân Tây'),
        Commune(name: 'Xã Thạnh Phú'),
        Commune(name: 'Xã Xuân Đông'),
        Commune(name: 'Xã Xuân Tây'),
        Commune(name: 'Xã Thạnh Phước'),
        Commune(name: 'Xã Thạnh Phú'),
        Commune(name: 'Xã Thạnh Phong'),
        Commune(name: 'Xã Thạnh Lộc'),
        Commune(name: 'Xã Thạnh Qưới'),
        Commune(name: 'Xã Thạnh Quới'),
        Commune(name: 'Xã Thạnh Lợi'),
        Commune(name: 'Xã Thạnh Mỹ'),
        Commune(name: 'Xã Thạnh Tiến'),
        Commune(name: 'Xã Thạnh Xuân'),
        Commune(name: 'Xã Thạnh Thắng'),
      ],
    ),
    District(
      name: 'Huyện Vĩnh Hưng',
      communes: [
        Commune(name: 'Thị trấn Vĩnh Hưng'),
        Commune(name: 'Xã Hưng Điền'),
        Commune(name: 'Xã Hưng Điền B'),
        Commune(name: 'Xã Khánh Hưng'),
        Commune(name: 'Xã Thái Trị'),
        Commune(name: 'Xã Thái Trị A'),
        Commune(name: 'Xã Vĩnh Trị'),
        Commune(name: 'Xã Vĩnh Trị A'),
        Commune(name: 'Xã Vĩnh Hưng'),
        Commune(name: 'Xã Vĩnh Hưng A'),
        Commune(name: 'Xã Vĩnh Mỹ B'),
        Commune(name: 'Xã Vĩnh Mỹ A'),
        Commune(name: 'Xã Vĩnh Hậu'),
        Commune(name: 'Xã Vĩnh Hậu A'),
      ],
    ),
    District(
      name: 'Thị xã KĐT new city',
      communes: [
        Commune(name: 'Phường Tân Phú'),
        Commune(name: 'Phường Phúc Đạt'),
        Commune(name: 'Phường An Phú'),
        Commune(name: 'Phường Long Hưng'),
        Commune(name: 'Phường Bình Tân'),
        Commune(name: 'Phường Tân An'),
        Commune(name: 'Xã Hưng Định'),
        Commune(name: 'Phường An Bình'),
        Commune(name: 'Phường An Cơ'),
      ],
    ),
  ],
);
